name = "VortexTDA"
uuid = "fce2e195-78fd-42f7-a863-c94e5ae8c86f"
authors = ["Marko <mbudisic@clarkson.edu>"]
version = "0.1.0"

[deps]
PersistenceDiagrams = "90b4794c-894b-4756-a0f8-5efeb5ddf7ae"
Ripserer = "aa79e827-bd0b-42a8-9f10-2b302677a641"
